In [1]:
import numpy as np

In [2]:
array= np.array([[1,2,3],[2,3,4]])
print(array)

[[1 2 3]
 [2 3 4]]


In [3]:
#dimension
print('num of dim:',array.ndim)

num of dim: 2


In [5]:
print('shape:',array.shape)
print('size:',array.size)

shape: (2, 3)
size: 6


In [9]:
# np.float32 默认为64 
a = np.array([2,23,4],dtype=np.int)
print(a.dtype)

int64


In [10]:
b = np.array([[2,23,4],[2,3,4]])
print(b)

[[ 2 23  4]
 [ 2  3  4]]


In [12]:
a = np.zeros((3,4),dtype=int)
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [13]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
c = np.linspace(1,10,6).reshape(2,3)
c

array([[ 1. ,  2.8,  4.6],
       [ 6.4,  8.2, 10. ]])

In [18]:
a = np.array([10,20,30,40])
b = np.arange(4)
c = a - b
c

array([10, 19, 28, 37])

In [19]:
c = b**2
c

array([0, 1, 4, 9])

In [21]:
print(b==3)

[False False False  True]


In [22]:
a= np.array([[1,1],[0,1]]) 
b = np.arange(4).reshape(2,2)
print(a)
print(b)
c = a*b
print(c)

[[1 1]
 [0 1]]
[[0 1]
 [2 3]]
[[0 1]
 [0 3]]


In [23]:
# 矩阵点乘用np.dot
np.dot(a,b)

array([[2, 4],
       [2, 3]])

In [24]:
#创建随机矩阵
a = np.random.random((2,4))
a

array([[0.06960908, 0.58818955, 0.24720364, 0.43865762],
       [0.95119438, 0.11314487, 0.12844957, 0.53396077]])

In [26]:
print(np.sum(a))
print(np.min(a))
print(np.max(a))

3.0704094670772646
0.06960908219520656
0.9511943764328024


In [27]:
print(np.sum(a,axis=1))

[1.34365989 1.72674958]


In [29]:
a = np.arange(2,14).reshape(3,4)
a

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [31]:
print(np.argmax(a))

11


In [32]:
a = np.arange(14,2,-1).reshape(3,4)
a

array([[14, 13, 12, 11],
       [10,  9,  8,  7],
       [ 6,  5,  4,  3]])

In [42]:
print(np.sort(a))
print(np.mean(a,axis=1))

[[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]
[12.5  8.5  4.5]


In [36]:
print(np.transpose(a))
print(a.T)

[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]


In [38]:
print((a.T).dot(a))

[[332 302 272 242]
 [302 275 248 221]
 [272 248 224 200]
 [242 221 200 179]]


In [43]:
#所有数据>5&&<9
print(np.clip(a,5,9))

[[9 9 9 9]
 [9 9 8 7]
 [6 5 5 5]]


In [46]:
a= np.arange(3,15).reshape(3,4)
a

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [48]:
print(a[2])

[11 12 13 14]


In [49]:
a[1][1]

8

In [50]:
a[:,1]

array([ 4,  8, 12])

In [51]:
for row in a:
    print(row)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


In [53]:
for column in a.T:
    print(column)

[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


In [57]:
print(a.flatten())
for items in a.flat:
    print(items)

[ 3  4  5  6  7  8  9 10 11 12 13 14]
3
4
5
6
7
8
9
10
11
12
13
14


In [64]:
a = np.array([1,1,1])
b = np.array([2,2,2])
# vertical stack 上下合并
c = np.vstack((a,b))

In [66]:
c.shape

(2, 3)

In [67]:
# horizontal stack
d = np.hstack((a,b))
d

array([1, 1, 1, 2, 2, 2])

In [71]:
np.hstack((a.reshape(3,1),b.reshape(3,1)))

array([[1, 2],
       [1, 2],
       [1, 2]])

In [82]:
c = np.concatenate((a.reshape(3,1),b.reshape(3,1)),axis=1)
c

array([[1, 2],
       [1, 2],
       [1, 2]])

In [84]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [88]:
# split 等量分割
# array_split 不等分割
np.array_split(a,3,axis=1)

[array([[0, 1],
        [4, 5],
        [8, 9]]), array([[ 2],
        [ 6],
        [10]]), array([[ 3],
        [ 7],
        [11]])]