In [7]:
# 2020-3-3
# learn panda
import pandas as pd
df = pd.read_csv('top10_aqi.csv',encoding='utf-8')
df

City  AQI  PM2.5/1h  PM10/h  CO/1h  NO2/1h  O3/1h  O3/8h  SO2/1h
0   城市1    0         0       0   0.00       0      0      0       0
1   城市2    0         0       0   0.00       0      0      0       0
2   城市3    0         0       0   0.00       0      0      0       0
3   城市4   15         6      11   0.40      10     23     29       1
4   城市5   18        11      16   0.90      16     39     34       7
5   城市6   18         4      16   0.35       6     51     35       3
6   城市7   19         9      12   0.30      13     27     36       2
7   城市8   21         9      20   0.83      13     23     40       7
8   城市9   21         7      20   0.75      14     32     37      19
9  城市10   22         8      21   0.75      12     32     35       9

In [9]:
ndarray = df.values
type(ndarray)

numpy.ndarray

In [10]:
import numpy as np
n = np.random.randint(0,10,size=(4,5))
n

array([[7, 9, 8, 0, 3],
       [3, 7, 8, 9, 4],
       [8, 6, 5, 8, 1],
       [4, 3, 9, 3, 8]])

In [11]:
n+10

array([[17, 19, 18, 10, 13],
       [13, 17, 18, 19, 14],
       [18, 16, 15, 18, 11],
       [14, 13, 19, 13, 18]])

In [12]:
n2 = n/2
n2

array([[3.5, 4.5, 4. , 0. , 1.5],
       [1.5, 3.5, 4. , 4.5, 2. ],
       [4. , 3. , 2.5, 4. , 0.5],
       [2. , 1.5, 4.5, 1.5, 4. ]])

In [13]:
np.add(n,n)

array([[14, 18, 16,  0,  6],
       [ 6, 14, 16, 18,  8],
       [16, 12, 10, 16,  2],
       [ 8,  6, 18,  6, 16]])

## 矩阵的积 dot

In [17]:

n1 = np.random.randint(0,10,size=(2,3))
n2 = np.random.randint(0,10,size=(3,2))
print(n1,n2)
np.dot(n1,n2)

[[8 6 8]
 [7 2 5]] [[1 5]
 [9 0]
 [8 4]]


array([[126,  72],
       [ 65,  55]])

## 为缺失的维度补1
## 假定缺失的元素用已有值补充


In [19]:
m = np.ones((2,3))
a = np.arange(3)
print(m,a)
m+a

[[1. 1. 1.]
 [1. 1. 1.]] [0 1 2]


array([[1., 2., 3.],
       [1., 2., 3.]])

In [21]:
n1 = np.array([2,5,1,7,4])
def sortn(nd):
    for i in range(nd.size):
        for j in range(i,nd.size):
            if nd[i] > nd[j]:
                nd[i],nd[j] = nd[j],nd[i]   
    return nd
#sortn(n1)
    

array([1, 2, 4, 5, 7])

## 降低时间复杂度

In [31]:
def sortnd(nd):
    for i in range(nd.size):
        min_index = np.argmin(nd[i:])+i
        #print(min_index)
        nd[i],nd[min_index] = nd[min_index],nd[i]
    return nd

In [32]:
n2 = np.array([2,5,1,7,4])
sortnd(n2)

array([1, 2, 4, 5, 7])

### 快速排序

In [34]:
n2.sort()
n2

array([1, 2, 4, 5, 7])

### n1.sort() 改变n1的值
### n2 = np.sort(n1)  不改变n1的值

In [35]:
nd = np.random.randint(0,150,size=20)
nd

array([124, 131, 106,  89,   5,  76,   5,  66,  30, 129,  19,  66, 141,
       103,  27,   6, 123, 111,  48,  65])

####  k为正，最小的K个数
#### k为负，最大的K个数

In [38]:
np.partition(nd,-5)

array([ 48,   6,  27,  66,   5,  19,   5,  65,  30,  66, 106,  76,  89,
       103, 111, 123, 124, 141, 131, 129])

In [39]:
np.partition(nd,-5)[-5:]

array([123, 124, 141, 131, 129])